"""The Markdown body of ``STATE.md``, as a projection of its frontmatter.

The frontmatter was always the source of truth, and the body was always prose
somebody typed. Every formal write updated the first and carried the second
through untouched, so the two drifted apart the moment a phase closed: the
frontmatter said the project had moved on, and the body underneath it still
described the phase before, by name, with its branch and its task list.

A file that contradicts itself is worse than a file with less in it. Whoever
opens ``STATE.md`` reads the prose first — it is the part written for humans —
and the prose was the stale half.

So the body stops being authored and becomes **generated**. It mirrors the
frontmatter and nothing else, it is rewritten by every formal state write, and
it is never read back: no kernel decision consults it, which is what makes
regenerating it safe. The plan seal does not cover it either — the fingerprint
hashes ``PLAN.md`` and ``TASKS.md`` alone.

Prose that is *not* a mirror of state survives, because a projection has no
opinion about it. Wrap it:

    <!-- kernel:preserve -->
    Anything here is carried forward verbatim, every write, forever.
    <!-- /kernel:preserve -->

Bodies written before this module have no fence, and everything in them is a
mirror by construction — that is the defect. They are replaced. The previous
text is not lost; it is in the repository's history, and its substance belongs
in ``DECISIONS.md``, ``EVIDENCE.md`` and the phase handoff, which is where the
body itself always told people to keep it.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Mapping, Optional, Sequence

#: Opens and closes a region the projection must not touch.
PRESERVE_OPEN = "<!-- kernel:preserve -->"
PRESERVE_CLOSE = "<!-- /kernel:preserve -->"

_PRESERVE_PATTERN = re.compile(
    r"{}\n?(.*?)\n?{}".format(re.escape(PRESERVE_OPEN), re.escape(PRESERVE_CLOSE)),
    re.DOTALL,
)

#: Deliberately does **not** spell the fence markers out. The banner is part of
#: the generated body, and a body that quotes its own fence would be captured by
#: the next call to :func:`extract_preserved` and then re-emitted inside a
#: fence — growing one nesting level per write, forever. The marker names are
#: given in words instead, and the module docstring shows the literal form.
_BANNER = (
    "<!-- Generated by the Agent Framework kernel from the frontmatter above. "
    "Edits are overwritten by the next formal state write. To keep prose here, "
    "wrap it in a kernel:preserve HTML comment fence — see "
    "kernel/runtime/state_body.py. -->"
)


def _mapping(value: Any) -> Dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


def _sequence(value: Any) -> List[Any]:
    return list(value) if isinstance(value, Sequence) and not isinstance(value, str) else []


def _cell(value: Any) -> str:
    """One table cell: never empty, never a pipe, never a stale `None`."""

    if value is None or value == "":
        return "—"
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return str(value).replace("|", "\\|")


def _code(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return "`{}`".format(_cell(value))


def extract_preserved(body: Optional[str]) -> str:
    """The fenced regions of ``body``, in order, joined by a blank line.

    Returns the empty string when there is no fence — which is every body
    written before this module existed.
    """

    if not body:
        return ""
    blocks = [match.strip("\n") for match in _PRESERVE_PATTERN.findall(body)]
    return "\n\n".join(block for block in blocks if block.strip())


def _identification(state: Mapping[str, Any]) -> List[str]:
    project = _mapping(state.get("project"))
    milestone = _mapping(state.get("milestone"))
    phase = _mapping(state.get("phase"))
    git = _mapping(state.get("git"))
    task = _mapping(state.get("current_task"))

    rows = [
        ("Project", _cell(project.get("name"))),
        ("Status", _code(state.get("status"))),
        ("Execution mode", _code(state.get("execution_mode") or "critical")),
    ]
    # A milestone or phase whose fields are all null is not "unnamed", it is
    # absent — a row of em dashes would only make the reader wonder what it lost.
    if milestone.get("id") or milestone.get("name"):
        rows.append(
            (
                "Milestone",
                "{} ({})".format(
                    _cell(milestone.get("name")), _code(milestone.get("id"))
                ),
            )
        )
    if phase.get("id") or phase.get("name"):
        rows.append(
            (
                "Phase",
                "{} ({}) — {}".format(
                    _cell(phase.get("name")),
                    _code(phase.get("id")),
                    _code(phase.get("status")),
                ),
            )
        )
    rows.append(
        (
            "Current task",
            "{} — {}".format(_code(task.get("id")), _code(task.get("status")))
            if task.get("id")
            else "—",
        )
    )
    if git:
        rows.append(("Branch", _code(git.get("working_branch"))))
        rows.append(("Base branch", _code(git.get("base_branch"))))
    rows.append(("Updated", "{} by {}".format(
        _cell(state.get("updated_at")), _cell(state.get("updated_by"))
    )))

    lines = ["## Identification", "", "| Field | Value |", "| --- | --- |"]
    lines.extend("| {} | {} |".format(name, value) for name, value in rows)
    return lines


def _next_operation(state: Mapping[str, Any]) -> List[str]:
    action = _mapping(state.get("next_action"))
    operation = action.get("operation") or "none"
    target = action.get("target")
    rendered = operation if not target else "{} -> {}".format(operation, target)

    lines = ["## Next operation", "", "```text", rendered, "```"]

    blocked = state.get("blocked_from")
    if blocked:
        lines.extend(
            ["", "Blocked from `{}`; the guard that refused it still stands.".format(blocked)]
        )
    return lines


def _plan_revision(state: Mapping[str, Any]) -> List[str]:
    revision = _mapping(state.get("plan_revision"))
    if not revision:
        return []
    sealed = bool(revision.get("fingerprint"))
    lines = [
        "## Plan revision",
        "",
        "| Field | Value |",
        "| --- | --- |",
        "| Version | {} |".format(_cell(revision.get("version"))),
        "| Sealed | {} |".format("yes" if sealed else "**no**"),
        "| Decision | {} |".format(_code(revision.get("decision_id"))),
        "| Fingerprint | {} |".format(_code(revision.get("fingerprint"))),
        "| Evidence | {} |".format(_code(revision.get("evidence"))),
    ]
    return lines


def _artifacts(state: Mapping[str, Any]) -> List[str]:
    artifacts = _mapping(state.get("artifacts"))
    if not artifacts:
        return []
    lines = ["## Documents", "", "| Artifact | Path |", "| --- | --- |"]
    for name in sorted(artifacts):
        lines.append("| {} | {} |".format(name, _code(artifacts[name])))
    return lines


def _gates(state: Mapping[str, Any]) -> List[str]:
    gates = _mapping(state.get("gates"))
    if not gates:
        return []
    lines = ["## Gates", "", "| Gate | Status |", "| --- | --- |"]
    for name in sorted(gates):
        lines.append("| {} | {} |".format(name, _code(gates[name])))
    return lines


def _open_items(state: Mapping[str, Any]) -> List[str]:
    """Blockers and decisions still owed an answer."""

    blockers = [
        item
        for item in _sequence(state.get("blockers"))
        if isinstance(item, Mapping)
        and item.get("status") not in {"resolved", "waived"}
    ]
    decisions = [
        item for item in _sequence(state.get("open_decisions")) if isinstance(item, Mapping)
    ]
    if not blockers and not decisions:
        return ["## Open items", "", "None. No blocker and no decision is waiting."]

    lines = ["## Open items", ""]
    if blockers:
        lines.extend(["### Blockers", "", "| ID | Status | Summary |", "| --- | --- | --- |"])
        for item in blockers:
            lines.append(
                "| {} | {} | {} |".format(
                    _code(item.get("id")),
                    _code(item.get("status")),
                    _cell(item.get("summary")),
                )
            )
        lines.append("")
    if decisions:
        lines.extend(["### Decisions", "", "| ID | Unblocks | Question |", "| --- | --- | --- |"])
        for item in decisions:
            lines.append(
                "| {} | {} | {} |".format(
                    _code(item.get("id")),
                    _code(item.get("unblocks")),
                    _cell(item.get("summary") or item.get("question")),
                )
            )
    return [line for line in lines if line is not None]


def _completed_phases(state: Mapping[str, Any]) -> List[str]:
    phases = [
        item for item in _sequence(state.get("completed_phases")) if isinstance(item, Mapping)
    ]
    if not phases:
        return []
    lines = ["## Completed phases", "", "| ID | Name | Status |", "| --- | --- | --- |"]
    for item in phases:
        lines.append(
            "| {} | {} | {} |".format(
                _code(item.get("id")), _cell(item.get("name")), _code(item.get("status"))
            )
        )
    return lines


def _last_transition(state: Mapping[str, Any]) -> List[str]:
    transition = _mapping(state.get("last_transition"))
    if not transition:
        return []
    return [
        "## Last transition",
        "",
        "`{}` → `{}` at {}, by {}.".format(
            _cell(transition.get("from")),
            _cell(transition.get("to")),
            _cell(transition.get("at")),
            _cell(transition.get("by")),
        ),
        "",
        _cell(transition.get("reason")),
    ]


def render_state_body(state: Mapping[str, Any], preserved: str = "") -> str:
    """The whole body, generated. ``preserved`` is appended verbatim."""

    state = _mapping(state)
    persistent = isinstance(state.get("gates"), Mapping)

    sections: List[List[str]] = [
        [
            "# Project State",
            "",
            _BANNER,
            "",
            "The frontmatter above is the source of truth. This body mirrors it and "
            "is rewritten by every formal state write. Requirements, plans, "
            "decisions, evidence and handoff prose belong in the artifacts listed "
            "below, not here.",
        ],
        _identification(state),
        _next_operation(state),
    ]
    if persistent:
        sections.extend(
            [
                _plan_revision(state),
                _gates(state),
                _open_items(state),
                _completed_phases(state),
                _last_transition(state),
            ]
        )
    sections.append(_artifacts(state))

    rendered = "\n\n".join("\n".join(block) for block in sections if block)
    body = rendered.rstrip("\n") + "\n"

    if preserved.strip():
        body += "\n{}\n{}\n{}\n".format(PRESERVE_OPEN, preserved.strip("\n"), PRESERVE_CLOSE)
    return body


def project_state_body(state: Mapping[str, Any], existing_body: Optional[str] = None) -> str:
    """Regenerate the body, carrying forward whatever was fenced for keeping."""

    return render_state_body(state, extract_preserved(existing_body))
